//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:22:44 PM EET 
//


package com.DTP.dailyTimePlaner.XML.org.itroi.user;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for name.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="name">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OneToAll"/>
 *     &lt;enumeration value="OneToSelf"/>
 *     &lt;enumeration value="OneToAnyone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "groupRoleName")
@XmlEnum
public enum GroupRoleName {

    @XmlEnumValue("OneToAll")
    ONE_TO_ALL("OneToAll"),
    @XmlEnumValue("OneToSelf")
    ONE_TO_SELF("OneToSelf"),
    @XmlEnumValue("OneToAnyone")
    ONE_TO_ANYONE("OneToAnyone");
    private final String value;

    GroupRoleName(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupRoleName fromValue(String v) {
        for (GroupRoleName c: GroupRoleName.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
