//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:22:44 PM EET 
//


package com.DTP.dailyTimePlaner.XML.org.itroi.user;

import com.DTP.dailyTimePlaner.XML.org.itroi.entity.Entity;
import org.springframework.security.core.GrantedAuthority;

import javax.persistence.Column;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "roleType")
@javax.persistence.Entity(name = "role")
public class RoleType
        extends Entity
        implements GrantedAuthority {

    @Column(name = "name",
            columnDefinition = "VARCHAR(15)",
            nullable = false,unique = true)
    protected String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getAuthority() {
        return name;
    }}
