//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:22:44 PM EET 
//


package com.DTP.dailyTimePlaner.XML.org.itroi.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import com.DTP.dailyTimePlaner.XML.org.itroi.entity.Entity;


/**
 * <p>Java class for userType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="userType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.itroi.org/entity}Entity">
 *       &lt;sequence>
 *         &lt;element name="userValue" type="{http://www.itroi.org/user}userType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userType", propOrder = {
    "userValue"
})
public class UserType
    extends Entity
{

    protected com.DTP.dailyTimePlaner.XML.org.itroi.user.UserType userValue;

    /**
     * Gets the value of the userValue property.
     * 
     * @return
     *     possible object is
     *     {@link com.DTP.dailyTimePlaner.XML.org.itroi.user.UserType }
     *     
     */
    public com.DTP.dailyTimePlaner.XML.org.itroi.user.UserType getUserValue() {
        return userValue;
    }

    /**
     * Sets the value of the userValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.DTP.dailyTimePlaner.XML.org.itroi.user.UserType }
     *     
     */
    public void setUserValue(com.DTP.dailyTimePlaner.XML.org.itroi.user.UserType value) {
        this.userValue = value;
    }

}
