//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:22:44 PM EET 
//


package com.DTP.dailyTimePlaner.domain;


import javax.persistence.Column;

@javax.persistence.Entity(name = "state_task")
public class StatusType
    extends Entity
{
    @Column(name = "name",
            columnDefinition = "VARCHAR(45)",
            nullable = false)
    protected String name;

    public StatusType() {
        super();
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
