//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 05:22:44 PM EET 
//


package com.DTP.dailyTimePlaner.domain;

import com.DTP.dailyTimePlaner.domain.TaskPrefab;

import javax.persistence.Column;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

@javax.persistence.Entity(name = "taskXMLTest")
public class TaskType extends TaskPrefab
{
    @Column(name="TASK_DURATION",
            columnDefinition = "TIME")
    protected Date duration;

    @Column(name = "TASK_TIME",
            columnDefinition = "TIME",
            nullable = false)
    protected Date time;

    public Date getDuration() {
        return duration;
    }

    public void setDuration(Date duration) {
        this.duration = duration;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public void setDateTimeDuration(String taskDete, String timeStart, String timeFinish) throws ParseException {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date time;
        time = dateFormat.parse(taskDete);
        this.setDate(time);
        dateFormat = new SimpleDateFormat("hh:mm");
        time = dateFormat.parse(timeStart);
        this.setTime(time);
        time = dateFormat.parse(timeFinish);
        this.setDuration(time);
    }
}
